# -*- coding: utf-8 -*-
"""ml_model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TiNzUQYG6Q1uu4xIX31jbGhFiyM_KLZV
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

patients = pd.read_csv('patients.csv', parse_dates = ['arrival_date', 'departure_date'])
staff = pd.read_csv('staff_schedule.csv')
services = pd.read_csv('services_weekly.csv')

print("Patients")
patients['length_of_stay'] = (patients['departure_date'] - patients['arrival_date']).dt.days + 1
patients['week'] = patients['arrival_date'].dt.isocalendar().week.astype(int)

print(f"Shape: {patients.shape}")
print(f"Columns: {patients.columns}")
print(f"Data Types: {patients.dtypes}")
patients.head()

patients_agg = patients.groupby(['week', 'service']).agg(
    new_patients=('patient_id', 'count'),
    avg_age=('age', 'mean'),
    avg_los=('length_of_stay', 'mean'),
    avg_satisfaction=('satisfaction', 'mean')
    ).reset_index()

patients_agg.head()

print("Staff")
print(f"Shape: {staff.shape}")
print(f"Columns: {staff.columns}")
print(f"Data Types: {staff.dtypes}")
staff.head()

staff_agg = staff.groupby(['week', 'service']).agg(
    staff_present=('present', 'sum'),
    staff_count=('staff_id', 'nunique')
    ).reset_index()

staff_agg.head()

print("Services")
services['occupancy_rate'] = services['patients_admitted'] / services['available_beds']
services['occupancy_rate'] = services['occupancy_rate'].clip(0, 1)
print(f"Shape: {services.shape}")
print(f"Columns: {services.columns}")
print(f"Data Types: {services.dtypes}")
services.head()

merged = services.merge(patients_agg, on=['week', 'service'], how='left') \
                 .merge(staff_agg, on=['week', 'service'], how='left')

print(merged.dtypes)
merged.head()

merged[['new_patients', 'avg_age', 'avg_los', 'avg_satisfaction',
            'staff_present', 'staff_count']] = merged[[
            'new_patients', 'avg_age', 'avg_los',
            'avg_satisfaction', 'staff_present', 'staff_count'
            ]].fillna(0)

merged.to_csv("cleaned_hospital_dataset.csv", index=False)

# Exploratory Data Analysis

print("=== BASIC INFO ===")
print(merged.info())
print("\nMissing values:\n", merged.isna().sum())

plt.figure(figsize=(7,4))
sns.histplot(merged['occupancy_rate'], bins=20, kde=True)
plt.title("Distribution of Bed Occupancy Rate")
plt.xlabel("Occupancy Rate")
plt.ylabel("Frequency")
plt.show()

plt.figure(figsize=(10,5))
sns.lineplot(data=merged, x="week", y="occupancy_rate", hue="service")
plt.title("Weekly Occupancy Rate by Service")
plt.ylabel("Occupancy Rate")
plt.show()

plt.figure(figsize=(6,4))
sns.scatterplot(data=merged, x="patients_request", y="occupancy_rate", hue="service")
plt.title("Patients Request vs Occupancy Rate")
plt.show()

numeric_cols = merged.select_dtypes(include=['int64', 'float64'])

plt.figure(figsize=(10,7))
sns.heatmap(numeric_cols.corr(), annot=True, cmap="coolwarm")
plt.title("Correlation Heatmap")
plt.show()

plt.figure(figsize=(7,5))
sns.scatterplot(data=merged, x='staff_present', y='occupancy_rate', hue="service")
plt.title("Staff Present vs Occupancy Rate")
plt.show()

high_occ = merged[merged['occupancy_rate'] > 0.95]
print("\nWeeks with >95% occupancy:\n")
print(high_occ[['week', 'service', 'occupancy_rate', 'patients_request', 'patients_admitted']])

df = merged.copy()

df['ICU_demand_level'] = df.apply(lambda row:
    ('high' if row['service'] == 'ICU' and row['occupancy_rate'] >= 0.95 else
     'moderate' if row['service'] == 'ICU' and row['occupancy_rate'] >= 0.80 else
     'low' if row['service'] == 'ICU' else None),
    axis=1
)

def shortage_level(row):
    ratio = row['staff_present'] / row['staff_count']
    if ratio >= 0.9: return 'low'
    elif ratio >= 0.7: return 'moderate'
    else: return 'high'

df['staff_shortage_level'] = df.apply(shortage_level, axis=1)

print(df.dtypes)
df.head()

#Bed Occupancy Rate

bor_df = df.copy()


cat_cols = bor_df.select_dtypes(include=['object']).columns
print("Categorical columns:", cat_cols)

bor_df = pd.get_dummies(bor_df, columns=cat_cols, drop_first=False)

x_bor = bor_df.drop(columns=['occupancy_rate'])
y_bor = bor_df['occupancy_rate']

print("X shape:", x_bor.shape)
print("Y shape:", y_bor.shape)
print("\nX columns:", x_bor.columns)

#test
x_bor_train, x_bor_test, y_bor_train, y_bor_test = train_test_split(
    x_bor, y_bor, test_size=0.2, random_state=42
)

scaler = StandardScaler()
x_bor_train_scaled = scaler.fit_transform(x_bor_train)
x_bor_test_scaled = scaler.transform(x_bor_test)

from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(
    n_estimators=300,
    max_depth=None,
    min_samples_split=2,
    random_state=42
)

model.fit(x_bor_train_scaled, y_bor_train)

y_bor_pred = model.predict(x_bor_test_scaled)

mae = mean_absolute_error(y_bor_test, y_bor_pred)
rmse = np.sqrt(mean_squared_error(y_bor_test, y_bor_pred))
r2 = r2_score(y_bor_test, y_bor_pred)

print("Model Performance:")
print("MAE :", mae)
print("RMSE:", rmse)
print("R²   :", r2)

jitter = 0.005
x_jittered = y_bor_test + np.random.uniform(-jitter, jitter, size=len(y_bor_test))
y_jittered = y_bor_pred + np.random.uniform(-jitter, jitter, size=len(y_bor_pred))

colors = []
for val in y_bor_test:
    if val >= 0.95:
        colors.append('red')
    elif val >= 0.7:
        colors.append('yellow')
    else:
        colors.append('green')

plt.figure(figsize=(8,5))
plt.scatter(x_jittered, y_jittered, c=colors, alpha=0.7)
plt.plot([y_bor_test.min(), y_bor_test.max()], [y_bor_test.min(), y_bor_test.max()], linestyle='--', color='black', label='Perfect Prediction')
plt.xlabel("Actual Occupancy Rate")
plt.ylabel("Predicted Occupancy Rate")
plt.title("Actual vs Predicted Bed Occupancy Rate with Threshold Colors")
plt.legend()
plt.show()

"""
how to implement
if predicted_occupancy >= 0.95:
    alert = "RED: Capacity critical!"
elif predicted_occupancy >= 0.7:
    alert = "YELLOW: High occupancy"
else:
    alert = "GREEN: Safe occupancy"
"""

residuals = y_bor_test - y_bor_pred

plt.figure(figsize=(8,5))
plt.scatter(y_bor_pred, residuals)
plt.axhline(0, color='red', linestyle='--')
plt.xlabel("Predicted")
plt.ylabel("Residuals (Actual - Predicted)")
plt.title("Residual Plot")
plt.show()

#ICU Demand Random Forest

icu_df = df.copy()

icu_df = df[df['service'] == 'ICU'].copy()
icu_df = icu_df.drop(columns=['service'])

cat_cols = icu_df.select_dtypes(include=['object']).columns.tolist()
if 'ICU_demand_level' in cat_cols:
    cat_cols.remove('ICU_demand_level')
icu_df = pd.get_dummies(icu_df, columns=cat_cols, drop_first=False)


X_icu = icu_df.drop(columns=['ICU_demand_level'])
y_icu = icu_df['ICU_demand_level']

X_icu_train, X_icu_test, y_icu_train, y_icu_test = train_test_split(
    X_icu, y_icu, test_size=0.2, random_state=42, stratify=y_icu
)

icu_model = RandomForestClassifier(
    n_estimators=300,
    max_depth=None,
    min_samples_split=2,
    random_state=42
)
icu_model.fit(X_icu_train, y_icu_train)

y_icu_pred = icu_model.predict(X_icu_test)
print("=== ICU Model Performance ===")
print("Accuracy:", accuracy_score(y_icu_test, y_icu_pred))
print("Confusion Matrix:\n", confusion_matrix(y_icu_test, y_icu_pred))
print("Classification Report:\n", classification_report(y_icu_test, y_icu_pred))

new_icu_data = icu_df.drop(columns=['ICU_demand_level']).head(5)

new_icu_data_encoded = pd.get_dummies(new_icu_data)

for col in X_icu.columns:
    if col not in new_icu_data_encoded:
        new_icu_data_encoded[col] = 0

new_icu_data_encoded = new_icu_data_encoded[X_icu.columns]

new_icu_data['ICU_demand_level'] = icu_model.predict(new_icu_data_encoded)

alert_map = {'low': 'Green', 'moderate': 'Yellow', 'high': 'Red'}
new_icu_data['ICU_demand_alert'] = new_icu_data['ICU_demand_level'].map(alert_map)

print("\n=== ICU Alerts for New Data ===")
print(new_icu_data[['occupancy_rate', 'ICU_demand_level', 'ICU_demand_alert']])

#Staff Shortage Prediction

staff_df = df.copy()

cat_cols_staff = staff_df.select_dtypes(include=['object']).columns.tolist()
if 'staff_shortage_level' in cat_cols_staff:
    cat_cols_staff.remove('staff_shortage_level')

staff_df = pd.get_dummies(staff_df, columns=cat_cols_staff, drop_first=False)

X_staff = staff_df.drop(columns=['staff_shortage_level'])
y_staff = staff_df['staff_shortage_level']

X_staff_train, X_staff_test, y_staff_train, y_staff_test = train_test_split(
    X_staff, y_staff, test_size=0.2, random_state=42, stratify=y_staff
)

staff_model = RandomForestClassifier(
    n_estimators=300,
    random_state=42
)
staff_model.fit(X_staff_train, y_staff_train)

y_staff_pred = staff_model.predict(X_staff_test)

print("=== STAFF SHORTAGE MODEL PERFORMANCE ===")
print("Accuracy:", accuracy_score(y_staff_test, y_staff_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_staff_test, y_staff_pred))
print("\nClassification Report:\n", classification_report(y_staff_test, y_staff_pred))

